Add the section Mallet deploy contract
PortalNetwork/cns pull request #1
Opened 2018-09-23 03:59 UTC by johnny7861532

2018-09-23 07:31 UTC, PhyrexTsai requested changes

2018-09-23 07:31 UTC, PhyrexTsai commented on README.md
> +- [Using Mallet To Deploy Contract](https://github.com/johnny7861532/cns/blob/master/depoly_md/Cardano%20install%20Mallet%20to%20deploy%20and%20interact%20with%20smart%20contract.md)
You can use relative path of the file, just like (./docs/INTRODUCTION.md)

2018-09-23 07:31 UTC, PhyrexTsai commented on depoly_md/Cardano install Mallet to deploy and interact with smart contract.md
> +Before we can start to interact with Cardano
You can use ``` wrap this section

2018-09-23 07:31 UTC, PhyrexTsai commented on depoly_md/Cardano install Mallet to deploy and interact with smart contract.md
> +You cna also check the transaciton receipt with `$getReceipt`
You can

2018-09-23 07:31 UTC, PhyrexTsai commented on depoly_md/Cardano install Mallet to deploy and interact with smart contract.md
> +![螢幕快照 2018-09-21 下午3.56.42](https://github.com/johnny7861532/cns/blob/master/depoly_md/translate.png)
Please user the relative path for this image

2018-09-23 07:52 UTC, johnny7861532 commented on depoly_md/Cardano install Mallet to deploy and interact with smart contract.md
> +You cna also check the transaciton receipt with `$getReceipt`
don't get  what do u mean this line of require.

2018-09-25 02:56 UTC, PhyrexTsai approved these changes

2018-09-25 02:56 UTC, merged